export const SET_LOADING = "SET_LOADING";
export const GET_TRACKS = "GET_TRACKS";
export const GET_TRACKS_REQUESTED = "GET_TRACKS_REQUESTED";
export const ADD_TO_PLAYLIST = "ADD_TO_PLAYLIST";
export const REMOVE_FROM_PLAYLIST = "REMOVE_FROM_PLAYLIST";
